### PR TITLE
Fix issues #322, #336

### LINKED ISSUE #336: [strong issue] (only iPad, iPhone XS etc.) - Offset when uiviewcontroller is working with "presentViewController".
**Describe the bug**
There are problems if a UIViewController is not represented by "push" but by "present". Then there is an erroneous calculation of the UINavigationBar position. This creates a strong offset. The relative position of the UIViewcontollers.view must be taken into account in the position of the device window.

**To Reproduce**
See screenshot animation
1. Run Demo **on iPad**, 
2. press on "table", 
3. scroll down and up .. see offset at the top.

**Expected behavior**
No offset. A correct calculation of the uinavigationbar.

**Screenshots**
https://imgur.com/a/YTxh8dx

**Demo Project**
https://github.com/StefaniOSApps/Example
Run Demo **on iPad**, press on "table", scroll down and up .. see offset at the top.

### PR DESCRIPTION
**Pull request by StefaniOSApps**
should fix #336

### CODE REVIEW

**Comment by StefaniOSApps** [comment]
should fix #322 large titles

**Comment by StefaniOSApps** [comment]
now it works **with transcluded style** ...

https://imgur.com/a/PBbzydg

**Comment by andreamazz** [comment]
Hi @StefaniOSApps 
thanks for the contribution. This PR is a little messy though, I rather avoid the deletion and reupload of the whole file. Also I'd like some context behind the decision to remove the `updateContentInset` call, which was there for a reason (it keeps the scrollbar from twitching). I agree it was problematic, but if we decide to remove it I rather do so in a separate PR.

**Comment by andreamazz** [comment]
I'll close this for now, if you can create a fresh PR with just that change (also, as suggested by Hound, keep a space after the comma), that'd be great.

**Pull request closed without merging**
