### PR TITLE
fixed Scrolling views that don't take up the entire screen Scroll up but don't come down #354

### PR DESCRIPTION
**Pull request by jwolkovitzs**
fixed Scrolling views that don't take up the entire screen Scroll up but don't come down #354

### CODE REVIEW

**Comment by andreamazz** [comment]
Hey @jwolkovitzs 
can you provide a bit more of context? I'm not sure I understand what's going on.

**Comment by andreamazz** [comment]
Hey @jwolkovitzs 
can you provide a bit more context about this PR?

**Comment by jwolkovitzs** [comment]
Example of nav bar not showing properly when the table view is not the entire view on iPhone Xr and the correct behavior with this fix

upworking
downworking
upbroken
downbroken

**Comment by andreamazz** [comment]
Sorry for the massive delay, merged. Thanks!

**Pull request merged**
