### PR TITLE
add delegate for notify the expanded value changed

### PR DESCRIPTION
**Pull request by DaidoujiChen**
Hello @andreamazz,

in my case, i need to know when the navagationbar expanded. so i'm implement delegate to do this.

### CODE REVIEW

**Comment by codingrogue** [comment]
I think the `willChange` variant could come in handy too, especially if you want to animate other UI parts in sync with the navigation bar!

**Comment by andreamazz** [comment]
Hi @codingrogue 
It's hard to tell when it `willChange` since it relies on the status of the gesture. I probably can expose the gesture status if that helps.

**Comment by codingrogue** [comment]
Actually it's already possible :-)

```
-(void)navigationBarDidChangeToCollapsed:(BOOL)collapsed
{
    if(!collapsed) {
        self.navBarStatusCollapsed = NO;
        self.navBarStatusExpanding = YES;
    } else {
        self.navBarStatusCollapsed  = YES;
        self.navBarStatusCollapsing = NO;
    }
}
-(void)navigationBarDidChangeToExpanded:(BOOL)expanded
{
    if(!expanded) {
        self.navBarStatusExpanded   = NO;
        self.navBarStatusCollapsing = YES;
    } else {
        self.navBarStatusExpanded  = YES;
        self.navBarStatusExpanding = NO;
    }
}
```

**Comment by andreamazz** [comment]
Well... in that case... :laughing:

**Pull request closed without merging**
